---
name: CI
on: [ push, pull_request ]
jobs:
  omnilint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/omnilint:0.4
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lpenz/ogle
      - uses: actions/checkout@v2
        with:
          path: ./ghaction-rust-coverage
      - run: docker pull rust:slim
      - uses: ./ghaction-rust-coverage
      - run: grep '^SF:' lcov.info
  dockerhub:
    needs: [ omnilint, test ]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.7
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ steps.version.outputs.version_docker_ci != 'null' }}
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_docker_ci }}

